name: Deployment Two
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint
              uses: npm run lint
    test:
        needs: lint # This job will only run if the lint job passes
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Test
              uses: npm run test
    deploy:
        needs: test # This job will only run if the test job passes
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Build code
              uses: npm run build
            - name: Deploy
              uses: npm run deploy