name: Run Jest Tests
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Check Out Code
            uses: actions/checkout@v2
          - name: Setup Node.js
            uses: actions/setup-node@v2
            with:
                node-version: '20.x'
          - name: Install Dependencies
            run: npm install
          - name: Run Jest Tests
            run: npm test
          - name: Test Report 
            uses: actions/report-artifact@v2
            if: always()
            with:
                name: Test Report
                path: report/
